### ISSUE TITLE
Job array subjobs are not being held after failing/requeueing 20 times.

### ISSUE THREAD

**Issue by Shrini-h** [PBSPro/pbspro#1118]
Currently run_count attribute of an instantiated subjob is not incremented for each retry by server to run it on mom and hence any exception or rejection by Mom to run it will result in to and fro transfer of subjob between server and mom for eternity causing unnecessary mom and server cpu time and log space.

**Comment by dilip-krishnan** [comment]
The question that comes here is, should we just held the failing subjob or the whole array job. Personally
I feel we should maintain the fail count in the parent job and at any point if the cumulatively failure of subjobs reaches to 20 we should held the whole array job instead of putting a hold on the failing subjob. 

This actually reminds me of a forum discussion on how the array job is percieved in PBS. AFAIK we consider array jobs as a part of single normal job, instead of considering each subjob as a normal job.  Here is the link to the discussion http://community.pbspro.org/t/understanding-array-jobs/212/2 .
