### ISSUE TITLE
jobscript_max_size is not working.

### ISSUE THREAD

**Issue by TOMO-Uemoto** [PBSPro/pbspro#1159]
Job runs despite limiting jobscript_max_size to 1b.

[test@ohpc137pbsib-sms ~]$ qsub --version
pbs_version = 19.1.1
[test@ohpc137pbsib-sms ~]$

[root@ohpc137pbsib-sms ~]# qmgr -c "p s" | grep jobscript_max_size
[root@ohpc137pbsib-sms ~]# qmgr -c "set server jobscript_max_size = 1"
[root@ohpc137pbsib-sms ~]# qmgr -c "p s" | grep jobscript_max_size
set server jobscript_max_size = 1b
[root@ohpc137pbsib-sms ~]#

[test@ohpc137pbsib-sms ~]$ wc -c yes.sh
3897 yes.sh
[test@ohpc137pbsib-sms ~]$

[test@ohpc137pbsib-sms ~]$ ls -l yes.sh
-rw-rw-r-- 1 test test 3897 Jun 10 15:00 yes.sh
[test@ohpc137pbsib-sms ~]$

[test@ohpc137pbsib-sms ~]$ qsub yes.sh
1101.ohpc137pbsib-sms

<pre>
[test@ohpc137pbsib-sms` ~]$ qstat -an

ohpc137pbsib-sms:
                                                            Req'd  Req'd   Elap
Job ID          Username Queue    Jobname    SessID NDS TSK Memory Time  S Time
--------------- -------- -------- ---------- ------ --- --- ------ ----- - -----
1101.ohpc137pbs test     workq    yes         29423   1   1    --    --  R 00:00
   ohpc137pbsib-c001/1
[test@ohpc137pbsib-sms `~]$
</pre>

**Comment by arungrover** [comment]
This is a legit issue. I think the reason it is failing is because it is comparing the jobscript_max_size to a job script size from the job object. But, since the call is made from req_jobscript() method, the job object does not have the correct information about the size of the job script. 
We should rather pick the size of the job script from "preq" object.

This can be easily fixed if we replace "pj->ji_qs.ji_un.ji_newt.ji_scriptsz" with 
"preq->rq_ind.rq_jobfile.rq_size" in the following line - 

https://github.com/PBSPro/pbspro/blob/7a84d8b0df5f4c468dd9b21aae7cf4016044e090/src/server/req_quejob.c#L1447

**Comment by arungrover** [comment]
Fixed in PR #1285
