### ISSUE TITLE
scheduler may oversubscribe node with subjob

### ISSUE THREAD

**Issue by vchlum** [PBSPro/pbspro#1317]
I observed some oversubscribing. The scheduler may probably oversubscribe the node with a subjob. The problem is probably caused by the filter added in #872 .  The scheduler can miscount free resources now. The scheduler considers all not running subjobs to be gone (has_ghost_job==1). In order to fix this and do not break #791, I would suggest changing the filter added in #872 into filtering jobs in JOB_STATE_EXPIRED only.

Please, could someone check it with me (@arungrover)? I am not raising PR because I am not really sure yet.

**Comment by arungrover** [comment]
@vchlum can you elaborate more on this issue?
When scheduler detects that there are ghost jobs in the system, it reassigns the resources on the node according to the jobs it gets by querying server.
Are you worries that sub-jobs with exiting state will not be reported to scheduler because of the check added in #872 and this would mean that scheduler will start running jobs on the node while the mom is still processing exiting jobs? Maybe in that case filter should be that if the job is not in the running state or not in the exiting state then do not report those jobs to scheduler.

**Comment by vchlum** [comment]
@arungrover Yes, I think that is the issue - the exiting state of sub-jobs is not reported to the scheduler. In such a case, the scheduler set the has_ghost_job to true and reassigns the resources to the node incorrectly - it does not count the exiting sub-jobs. But the exiting sub-jobs can still be there. The exiting state can take a while... and meanwhile the oversubscribing can probably happen.

I think you are right that the filter that reports running or exiting sub-jobs in #872 is probably enough to fix this issue. The two states mean that a job occupies a node. My other question is: Is that policy in the right place? Shouldn't we send all the jobs to the scheduler and let it decide what states occupy a node?

**Comment by vchlum** [comment]
I can randomly reproduce the issue by submitting 'echo "sleep 1" | qsub -J 1-1000' into a system with two nodes and each node has 2 ncpus:
```
(JESSIE)vchlum@torque1:~$ pbsnodes -v torque2 | grep -E "cpus|jobs"
     pcpus = 2
     jobs = 1145[719].torque1.ics.muni.cz/0, 1145[723].torque1.ics.muni.cz/1, 1145[722].torque1.ics.muni.cz/1, 1145[720].torque1.ics.muni.cz/1
     resources_available.ncpus = 2
     resources_assigned.ncpus = 4
```

It happens even if the filter added in #872 is removed... So the problem may be somewhere else...

**Comment by vchlum** [comment]
Thank you for clarification @arungrover
